name: "Check for unacceptable PR"
on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/pr-regex-exclude@main
        with:
          # You will need to specify a regular expression in the syntax here:
          # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp
          # This is a string pattern, not a RegExp literal.
          
          # GitHub does not support an array or list as inputs to actions, so
          # for multiple paths, either use the | (pipe) character, or specify 
          # a JSON array of regular expressions. You must double-escape characters
          # if you use a JSON array.
          # '(dist/(.*)\.js)|(\.editorconfig)'
          # '[ "dist/(.*)\\.js", "\\.editorconfig" ]'
          exclude-regex: '<your RegExp here>'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
                   Thank you for submitting this PR, but it appears that at least one file in this request is against a part of our codebase that does not accept pull requests.

                   Please check the [contributing guide](./CONTRIBUTING.md) for more information.

                   I am a bot; this action was performed automatically.
