name: 'build-and-test'
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install
      - run: yarn run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          # This only tests *not* closing a PR
          exclude-regex: 'nonexistantfileregex'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Test message'
